### ISSUE TITLE
question about download

### ISSUE THREAD

**Issue by wanghechong** [harvardnlp/neural-template-gen#1]
Hi， 
Thanks your code very much, 
I want to know why the wb_aligned.tar.gz only contains the train.txt and valid txt, and when i want to download your pretrained mode and Viterbi Segmentations in the websit you provide (that is the (https://drive.google.com/drive/folders/1iv71Oq7cmXRY6h2jn0QzlYbbr0GwHCfA?usp=sharing) and (https://drive.google.com/file/d/1ON4ROs_coDNmVt3-JON4wK1Kc_NkIV2M/view?usp=sharing) i can not open the website and find the mode.  Sorry to disturbe you.

**Comment by swiseman** [comment]
Hi,

No problem: the reason wb_aligned.tar.gz doesn't contain test.txt is because I didn't modify the input/source format at all (unlike the E2E data), and so you can just use the test.box in the original WikiBio data. In particular, you can extract the test src lines in the exact same way as lines 126-137 of [data/make_wikibio_labedata.py](https://github.com/harvardnlp/neural-template-gen/blob/master/data/make_wikibio_labedata.py).

But hmm, I'm not sure why you can't download the models/segmentations. For the segmentations, Google Drive says it can't show a preview, but it does let me just download them. For the models, it seems to show the four models. I guess I can just email you the models/segmentations if you aren't able to download them from Google Drive. 

Edit: oh but what sort of error you do you get when you click on those links?

**Comment by swiseman** [comment]
I'm gonna close this issue, but let me know if you haven't figured this out.
