### ISSUE TITLE
Issue with generation

### ISSUE THREAD

**Issue by PExplorer** [harvardnlp/neural-template-gen#2]
Hello, 

Thank you for repository and the paper on learning neural templates. Although I have not understood the mathematics behind it completely, intuition explained in the paper helped me to understand the concept.  It would be great if you can post something on architecture and text data flow in detail .

I have following issues:

1. I have followed the steps in mentioned in Read.md for generating text from src_uniq_valid.txt. I have rerun segmentation part and used pretrained model. I am unable to debug it. What could be the issue? 

Traceback (most recent call last):
  File "chsmm.py", line 1376, in <module>
    gen_from_src()
  File "chsmm.py", line 1297, in gen_from_src
    gen_from_srctbl(src_tbl, top_temps, coeffs, src_line=src_line)
  File "chsmm.py", line 1203, in gen_from_srctbl
    len_lps, row2tblent, row2feats)
  File "chsmm.py", line 786, in gen_one_ar
    args.beamsz, corpus)
  File "chsmm.py", line 700, in temp_ar_bs
    inps.data[len(new_hyps)].copy_(row2feats[tblidx])
KeyError: tensor(1, device='cuda:0')

2. Can we do transfer learning of this pretrained model to new domain where very few labelled data available by fine tuning it? 

Thank you for your time,

**Comment by swiseman** [comment]
Hi,

1. It looks like this might be caused by using pytorch 0.4 rather than 0.3. In particular, `row2feats` wants an integer index, but `tblidx` can end up being a tensor when using pytorch 0.4. I think the easiest thing would be to use pytorch 0.3 or 0.3.1 if you can; otherwise, you can try calling `.item()` on the `wrd` variable which is used in computing `tblidx`. This might be somewhat precarious, though, because there are subtle bugs that can be introduced by replacing integers with tensors.

2. I haven't tried, but I think it would be difficult to transfer to a domain that isn't extremely similar. In particular, while some latent states capture relatively generic phenomena, others specialize quite a bit to particular phrases occurring in the data they're trained on.
