### ISSUE TITLE
questions about e2e dataset.

### ISSUE THREAD

**Issue by gwlgmz** [harvardnlp/neural-template-gen#4]
Your research is very interesting.
I have some problems. Firstly i made a small number of dataset in e2e format, about 20 lines, but encountered the following error.

Traceback (most recent call last):
  File "chsmm.py", line 946, in <module>
    add_eos=False, test=args.test)
  File "/home/hn/nlg/neural-template-gen-master/labeled_data.py", line 53, in __init__
    self.get_vocabs(os.path.join(path, 'train.txt'), train_src, thresh=thresh)
  File "/home/hn/nlg/neural-template-gen-master/labeled_data.py", line 131, in get_vocabs
    assert self.dictionary.idx2word[4 + len(self.genset) - 1] in self.genset
AssertionError

I also want to know whether the system supports Chinese data sets. I have the following problems when use Chinese directly.

Traceback (most recent call last):
  File "chsmm.py", line 955, in <module>
    train_cidxs.append(make_bwd_constr_idxs(args.L, x.size(0), constrs))
  File "/home/hn/neural-template-gen-master/utils.py", line 106, in make_bwd_constr_idxs
    cidxs[start].update([l*bsz + b for l in xrange(steps_fwd) if l+1 != clen])
IndexError: list index out of range

**Comment by swiseman** [comment]
Those assertions are checking that we've split the vocabulary into a subset that can be generated and a subset that can't (and must be copied), and that the subset that can be generated comes first (index-wise). My guess is the reason you're getting that error is that the script by default uses a minimum frequency threshold to prune words from the vocabulary, and since you only have 20 lines you end up pruning all words, and so you end up with an empty vocabulary. So you should be able to fix this by using `-thresh 0` when running the script.

Hmm, I've never tried the code with Chinese, but I don't know why it wouldn't work, assuming it's tokenized. It looks like the error you're getting there results from passing in a constraint tuple that has a start index that is longer than the sequence. So, my guess is the constraints you've made during preprocessing are wrong in some way; perhaps this is related to the previous issue?

**Comment by xiaozhi2015** [comment]
@gwlgmz 
Did you successfully apply it to Chinese datasets?
